CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE STUDENT(
	STUDENT_ID GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(200),
	CLASS VARCHAR(100),
	DIVISION CHAR(1),
	AGE SMALLINT,
	EMAIL VARCHAR(100),
	JOIN_DATE DATE,
	ROLLNO UPPER(SUBSTRING(NAME,1,4)) || STUDENT_ID
)

INSERT INTO student (name, class, division, age, email, join_date)
values ('Rahul','BCS',NULL,19,'prajwalgg99@gmail.com','2026-05-11')

SELECT * FROM student;

SELECT NAME,CLASS FROM STUDENT;

ALTER TABLE student 
ADD COLUMN ROLLNO VARCHAR(5);

UPDATE student
SET rollno = UPPER(SUBSTRING(name,1,4)) || student_id;

ALTER TABLE STUDENT
ADD COLUMN USELESS BIGINT;
ALTER TABLE STUDENT
DROP COLUMN USELESS;