-- operators in sql

-- arithematic operator : +,-,*,/,%
SELECT NAME,SALARY+500 AS NEW_SALARY FROM EMPLOYEES;

-- COMPARISION OPERATORS- >,<,=<,=>,!= OR <>
SELECT * FROM STUDENT WHERE AGE>20;

-- LOGICAL OPERATORS- AND, OR , NOT
SELECT * FROM STUDENT
WHERE CLASS LIKE '%H%' AND EMAIL LIKE '_a%';

-- SPECIAL OPERATORS

-- 1) IN operator
SELECT * FROM STUDENT 
WHERE CLASS IN ('cbse','bcs');

-- 2) BETWEEN operator
SELECT * FROM SALES
WHERE AMOUNT BETWEEN 5000 AND 100000;

-- 3) LIKE
SELECT * FROM SALES
WHERE PRODUCT LIKE '%e'

-- 4) IS NULL
SELECT * FROM SALES 
WHERE AMOUNT IS NULL;

-- 5) STRING OPERATORS

-- A) CONCATINATION OPERATOR
SELECT PRODUCT || ' SOLD AT ' || AMOUNT FROM SALES;